/*PROBLEM 29
Distinct Powers
Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.
How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100
*/

/* Libraries */
#include <stdio.h>

/* Function Prototypes */

void printresult(int);
void foundone(int, int);
void loadArray();
int search(int, int);   //input an int and exp to search for in the found array. 0 = not found 1 = found
int findsqrt(int);      //See if theres a square of the number and we can multiply exponents

/* Globals */

int NumberOfExponents = 101*100;
int total = 0;
int number = 2;
int exponent = 2;
int found[101*100][101];    // So i can store which terms are found [exp][int] 0,x where x is 1-100. 
                            // So dont count the first row. This has potential to be row 0-100 and
                            // columns 100*100 because we are multiplyng exponents together

int main()
{   
    loadArray();    //Loads the first column with the ints 0-100 and the rest as 0's
    int x = 2;
    int y = 2;      //We know all the 2's are distinct, because we havent done anyting else yet

    while (y <= 5){
        while(x <= 5){
            if(search(x, y) == 0){
                foundone(x, y);
            }
            x++;
        }
        x = 2;
        y++;
    }
    printresult(total);
    return 0;
}

/* All done, print out the results , results */
void printresult(int terms){
    printf(" The number of distnct terms is: %d \n", terms);

}

/* Found one and add it to the total [exp][num] */
void foundone(int exp, int num){
    total++;
    found[exp][num] = 1;
    printf("Found : %d^%d \n", num, exp);

}

/* Load the array with column 0 >> 1-100. All other columns get loaded with 0's. 
When I find a distint term, I will change it to a 1 */
void loadArray(){
    for (int y = 0; y < 101; y++){
        found[0][y] = y;
        for (int x = 1; x < NumberOfExponents; x++){
            found[x][y] = 0;
        }
    }
}

/* input an int and exp to search for in the found array. 0 = not found 1 = found */
int search(int exp, int num){
    if(found[exp][num] == 1){
        return 1;
    }
    else{
        return 0;
    }
}   

/* Search if there is a square root of a number, return the square root or 0 if there isnt one */
int findsqrt(int num){
    int y = 2;
    while (y <= num / 2){
        if( num / y == y){
            return y;
        }
        y++;
    }
    return 0;
}